# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0006_auto_20171011_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midliner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('inheritance.champion',),
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('inheritance.champion',),
        ),
        migrations.AlterModelOptions(
            name='champion',
            options={'ordering': ['rank'], 'verbose_name': '챔피언'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='customers',
            field=models.ManyToManyField(related_name='providers', to='inheritance.Place'),
        ),
    ]
