# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0007_auto_20171012_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='customers',
        ),
        migrations.AddField(
            model_name='supplier',
            name='another_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='another_place_supplier', to='inheritance.Place'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supply_places',
            field=models.ManyToManyField(related_name='supply_place_set', to='inheritance.Place'),
        ),
    ]
