# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0010_auto_20171012_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inheritance.Student'),
        ),
    ]
