# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0011_auto_20171012_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='student',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supply_places',
            field=models.ManyToManyField(related_name='supply_place_set', related_query_name='supply_place', to='inheritance.Place'),
        ),
    ]
